FROM debian:latest

SHELL ["/bin/bash", "-c"]

USER root 

# Install dependencies
RUN apt-get update && \
apt-get install -y apt-transport-https \
     ca-certificates \
     curl \
     wget \
     gnupg2 \
     software-properties-common \
     g++ \ 
     sqlite3 \ 
     libsqlite3-dev \ 
     libtiff5-dev \  
     pkg-config \
     cmake \
     python3-pip \
     postgresql-client \
     libpq-dev \
     libgeos-dev \
     htop \
     libcurl4-openssl-dev \
     postgis

#-----------------------------
# install proj-9
ARG PROJ_VERSION=9.4.1
RUN wget https://download.osgeo.org/proj/proj-9.4.1.tar.gz && \
    tar xvzf proj-9.4.1.tar.gz && \
    cd proj-9.4.1 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . && \
    cmake --build . --target install
    
#-----------------------------
# Download GDAL v3.9.2 Source (ex. 3.9.2)
ARG GDAL_VERSION=3.9.2
RUN cd /root && \
    wget https://github.com/OSGeo/gdal/releases/download/v3.9.2/gdal-3.9.2.tar.gz && \
    tar xfv gdal-3.9.2.tar.gz && \
    cd gdal-3.9.2 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j48 install && \
    cd / && \
    rm -rf proj-9.4.1* && \
    cd /root && \
    rm -rf gdal* && \
    rm -rf /var/lib/apt/lists/* 

#-----------------------------
# Download Python 3.10.14 Source (ex. 3.10.14)
RUN apt-get update && apt-get install -y  build-essential \
                        zlib1g-dev \
                        libncurses5-dev \
                        libgdbm-dev \
                        libnss3-dev \
                        libssl-dev \ 
                        libreadline-dev \
                        libffi-dev \ 
                        libsqlite3-dev \
                        wget \  
                        libbz2-dev \
                        gcovr && \
                        wget https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tar.xz && \
                        tar xfv Python-3.10.14.tar.xz && \
                        cd Python-3.10.14 && \
                        ldconfig && \
                        ./configure --enable-optimizations && \
                        make -j48 install  

# Set LD_LIBRARY_PATH so that recompiled GDAL is used
ENV LD_LIBRARY_PATH /lib:/usr/lib:/usr/local/lib
