services:

      downloadmino-server-dev:
        build: 
          dockerfile: ./docker/homol/Dockerfile
        hostname: downloadmino-server-dev
        container_name: downloadmino-server-dev
        privileged: true
        ports:
          - '8282:8080'
        restart: always
        stdin_open: true
        tty: true
        volumes:
          - './:/APP/download-minio'
          - './dev/data:/data'
          - '/etc/localtime:/etc/localtime'
          - './dev/mnt/tmpfs:/mnt/tmpfs'
