[default]
HTTPS = false
DOWNLOAD = '/storage'
DOWNLOAD_URL = 's3.lapig.iesa.ufg.br'
MINIO_HOST = 'localhost'
MINIO_USER = 'admin' 
MINIO_PASSWORD = 'passadmin'
MINIO_PORT = 9000
BUCKET = 'ows'

MAPFILE = '/mnt/tmpfs/ows_runtime.map'
CACHE_MAP = 'app/data/'
FILE_MAP_CACH = 'ows.map.cache.lgobj'


DB_USER = 'user'
DB_PASSWORD = '123456'
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_DATABASE = 'gdb'

MONGODB_URL = 'localhost:27017'